replicaCount: 1

image:
  repository: quay.io/ecosystem-appeng/aiobs-metrics-api
  tag: 0.11.1

service:
  type: ClusterIP
  port: 8000

route:
  enabled: true
  host: ai-metrics-summarizer.example.com

config:
  prometheusUrl: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"

env:
  PYTHON_LOG_LEVEL: "INFO"

llm:
  url: ""
  apiToken: ""
  modelName: ""

# Contains all model details: external/internal, API key requirements, service mappings
modelConfig: {}


rbac:
  createGrafanaRole: true # User sets this to false if role already exists

